name: Deploy
on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: cd functions && npm install
      - name: Install global dependencies
        run: sudo npm install -g firebase-tools typescript
      - name: Test
        run: cd functions && npm test
      - name: Deploy to Firebase development
        if: github.ref == 'refs/heads/develop'
        run: firebase deploy -P dev --token=${{ secrets.FIREBASE_DEV_TOKEN }} --non-interactive
      - name: Deploy to Firebase production
        if: github.ref == 'refs/heads/master'
        run: firebase deploy -P prod --token=${{ secrets.FIREBASE_PROD_TOKEN }} --non-interactive
