name: Deploy
on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: cd functions && npm install
      - name: Install global dependencies
        run: sudo npm install -g firebase-tools typescript
      - name: Test
        run: cd functions && npm test
      - name: Deploy to Firebase development
        if: github.ref == 'refs/heads/develop'
        run: |
          printenv GOOGLE_JSON > creds.json
          firebase deploy -P dev --non-interactive
        env:
          GOOGLE_JSON: ${{ secrets.FIREBASE_DEV_JSON }}
          GOOGLE_APPLICATION_CREDENTIALS: creds.json
      - name: Deploy to Firebase production
        if: github.ref == 'refs/heads/master'
        run: |
          printenv GOOGLE_JSON > creds.json
          firebase deploy -P prod --non-interactive
        env:
          GOOGLE_JSON: ${{ secrets.FIREBASE_PROD_JSON }}
          GOOGLE_APPLICATION_CREDENTIALS: creds.json
