name: Test
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: cd functions && npm install
      - name: Install global dependencies
        run: sudo npm install -g firebase-tools typescript
      - name: Test
        run: cd functions && npm test
